// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DeviceAuthInfo {
    "user_code": string;
    "verification_uri": string;

    /** Creates a new DeviceAuthInfo instance. */
    constructor($$source: Partial<DeviceAuthInfo> = {}) {
        if (!("user_code" in $$source)) {
            this["user_code"] = "";
        }
        if (!("verification_uri" in $$source)) {
            this["verification_uri"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DeviceAuthInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): DeviceAuthInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DeviceAuthInfo($$parsedSource as Partial<DeviceAuthInfo>);
    }
}

export class StreamInfo {
    "user_name": string;
    "user_login": string;
    "game_name": string;
    "viewer_count": number;
    "title": string;

    /** Creates a new StreamInfo instance. */
    constructor($$source: Partial<StreamInfo> = {}) {
        if (!("user_name" in $$source)) {
            this["user_name"] = "";
        }
        if (!("user_login" in $$source)) {
            this["user_login"] = "";
        }
        if (!("game_name" in $$source)) {
            this["game_name"] = "";
        }
        if (!("viewer_count" in $$source)) {
            this["viewer_count"] = 0;
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamInfo($$parsedSource as Partial<StreamInfo>);
    }
}
