// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelLogin(): $CancellablePromise<void> {
    return $Call.ByID(119549686);
}

export function GetInjectionTexts(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(229984970).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetLoginStatus(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3756039400).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetSettings(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3985048828).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * LoadSavedToken loads the token from disk if it exists.
 */
export function LoadSavedToken(): $CancellablePromise<boolean> {
    return $Call.ByID(2109788831);
}

/**
 * Login starts the Device Code Grant Flow and begins polling for token.
 */
export function Login(): $CancellablePromise<$models.DeviceAuthInfo | null> {
    return $Call.ByID(1485395276).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Logout(): $CancellablePromise<void> {
    return $Call.ByID(12318777);
}

/**
 * RebuildQueue constructs the active queue based on Smart Round-Robin rules.
 */
export function RebuildQueue(): $CancellablePromise<void> {
    return $Call.ByID(1500578625);
}

/**
 * RefreshLiveStreamers fetches active live streams for followed channels.
 */
export function RefreshLiveStreamers(): $CancellablePromise<void> {
    return $Call.ByID(1965342780);
}

export function SaveInjectionTexts(css: string, html: string, js: string): $CancellablePromise<void> {
    return $Call.ByID(1526843541, css, html, js);
}

export function SaveSettings(initial: number, rotation: number, autoStart: number, language: string): $CancellablePromise<void> {
    return $Call.ByID(2482909975, initial, rotation, autoStart, language);
}

export function SaveWatchedTimes(): $CancellablePromise<void> {
    return $Call.ByID(1417415950);
}

/**
 * SetApp saves the Wails application reference for events and window control.
 */
export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(1309962740, app);
}

export function SetCurrentChannel(channel: string): $CancellablePromise<void> {
    return $Call.ByID(1164579925, channel);
}

export function SetSettingsOpen(open: boolean): $CancellablePromise<void> {
    return $Call.ByID(3902364168, open);
}

export function SetWindows(main: application$0.WebviewWindow | null, twitch: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(2078493282, main, twitch);
}

export function SkipStreamer(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1864214371).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StartAutoMode(currentChannel: string): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(929692853, currentChannel).then(($result: any) => {
        return $$createType1($result);
    });
}

export function StopAutoMode(): $CancellablePromise<void> {
    return $Call.ByID(3322590415);
}

export function SyncSubWindowPositions(): $CancellablePromise<void> {
    return $Call.ByID(3145282670);
}

export function TickSecond(): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(3394191746).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $models.DeviceAuthInfo.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
