//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backend$0 from "../../../../GennoBou/gnb-twview/backend/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "auto-state-changed": $$createType0,
        "device-auth-status": $$createType0,
        "login-status-changed": $$createType0,
        "streamer-switched": $$createType0,
        "streamers-updated": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = backend$0.StreamInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);

configure();
