// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as backend$0 from "../../../../GennoBou/gnb-twview/backend/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "auto-state-changed": { [_ in string]?: any };
            "device-auth-status": { [_ in string]?: any };
            "login-status-changed": { [_ in string]?: any };
            "streamer-switched": { [_ in string]?: any };
            "streamers-updated": backend$0.StreamInfo[];
        }
    }
}
